### PR TITLE
update profile photo

### PR DESCRIPTION
**Pull request by philschatz**
This updates the profile of `philschatz` to be even more professional.

Thanks @melaridi !

### CODE REVIEW

**Comment by RoyEJohnson** [comment]
@philschatz Got some conflicts now.

**Comment by philschatz** [comment]
Should be rebased now; I did `git rebase master` 😄

**Comment by dak** [comment]
@RoyEJohnson 
image

**Comment by RoyEJohnson** [comment]
@dak The interesting thing is that it doesn't seem to have changed the picture on the About Us page.

**Comment by dak** [comment]
@RoyEJohnson That's because it was merged to the `simplify-install` branch, not to `master`. I think Phil just wanted to see if somebody would merge it without fully reviewing it.

**Pull request merged**
