### PR TITLE
Revise build system

### PR DESCRIPTION
**Pull request by RoyEJohnson**
This is a PR against `anticipated-merge`, a merge of `exclude-settings.js-from-bundle` and `master`. That shows which changes are actually new for purposes of code review.

### CODE REVIEW

**Comment by philschatz** [comment]
A fix for the sourcemaps is started in #1003

**Comment by RoyEJohnson** [comment]
[Revise FE build process for faster updates and cleaner build output](https://trello.com/c/MrtCvyYo/519-revise-fe-build-process-for-faster-updates-and-cleaner-build-output)

**Comment by RoyEJohnson** [comment]
@philschatz Is this PR ok for merge with the understanding that #1003 will follow? The card in my previous comment is not being closed out; I'm attaching 1003 to it as well.

**Comment by philschatz** [comment]
In that case could the commits that remove the sourcemaps be removed from this PR? That way #1003 would not need to re-add them in.

**Comment by RoyEJohnson** [comment]
There's no commit devoted to removing sourcemaps. That was part of code relocation and other revisions.

**Comment by philschatz** [comment]
In that case can the code be re-added into this PR since it is not going the be removed?

**Pull request merged**
