### PR TITLE
Update heros for partners and subjects

### PR DESCRIPTION
**Pull request by RoyEJohnson**

### CODE REVIEW

**Comment by RoyEJohnson** [comment]
[Update Partners Hero](https://trello.com/c/2WlH6VoJ/415-update-partners-hero)

**Comment by RoyEJohnson** [comment]
[Update Subjects Hero](https://trello.com/c/44OgIQ7C/416-update-subjects-hero)

**Comment by Fredasaurus** [comment]
Pictures?

**Comment by RoyEJohnson** [comment]
@Fredasaurus Now in the cards.

**Comment by Fredasaurus** [comment]
Thanks,

**Pull request merged**
