### PR TITLE
New Press page

### PR DESCRIPTION
**Pull request by RoyEJohnson**
For: https://github.com/openstax/openstax.org/issues/2252

### CODE REVIEW

**Comment by RoyEJohnson** [comment]
Full width:
image

**Comment by RoyEJohnson** [comment]
iPad width:
image

**Comment by RoyEJohnson** [comment]
iPhone width:
image

**Review by Dantemss — APPROVED** [review]
The code seems fine to me. I think there are too many changes for me to be able to reason about the code. But send it to testing and see what happens.

**Pull request merged**
